### ISSUE TITLE
Interpolation Error Italic /dasiaoxia

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Alegreya-Sans#3]
interpolation error with /dasiaoxia.  
closing in on itself with increased weight.

check to see result in these glyphs
Alphadasiaoxia Alphadasiaoxiaprosgegrammeni Epsilondasiaoxia Etadasiaoxia Etadasiaoxiaprosgegrammeni Iotadasiaoxia Omicrondasiaoxia Upsilondasiaoxia Omegadasiaoxia Omegadasiaoxiaprosgegrammeni Alphadasiaoxiaprosgegrammeni.ss05 Etadasiaoxiaprosgegrammeni.ss05 Omegadasiaoxiaprosgegrammeni.ss05 alphadasiaoxia alphadasiaoxiaypogegrammeni epsilondasiaoxia etadasiaoxia etadasiaoxiaypogegrammeni iotadasiaoxia omicrondasiaoxia upsilondasiaoxia omegadasiaoxia omegadasiaoxiaypogegrammeni alphadasiaoxia.sc alphadasiaoxiaypogegrammeni.sc epsilondasiaoxia.sc etadasiaoxia.sc etadasiaoxiaypogegrammeni.sc iotadasiaoxia.sc omicrondasiaoxia.sc upsilondasiaoxia.sc omegadasiaoxia.sc omegadasiaoxiaypogegrammeni.sc Alphadasiaoxiaprosgegrammeni.sc.ss05 Etadasiaoxiaprosgegrammeni.sc.ss05 Omegadasiaoxiaprosgegrammeni.sc.ss05 alphadasiaoxiaypogegrammeni.sc.ss05 etadasiaoxiaypogegrammeni.sc.ss05 omegadasiaoxiaypogegrammeni.sc.ss05 dasiaoxia dasiaoxia.case

![:dasiaoxia case interp error Italic](https://user-images.githubusercontent.com/6576107/68824723-d1d3be80-0665-11ea-9c0b-bfa4a01a5f3a.png)

**Comment by cjdunn** [comment]
I believe this is the same nested component issue in fontmake (since the masters look good), referenced here: 
https://github.com/googlefonts/fontmake/issues/595#issuecomment-554013134

The heaviest master looks good, that same named instance in the var font has the problem (screenshot attached) 
![master vs named instance](https://user-images.githubusercontent.com/3900241/68886124-83b1d000-06e4-11ea-84c2-9e625f6960d6.png)

**Comment by cjdunn** [comment]
This issue is fixed in my PR: https://github.com/TypeNetwork/Alegreya-Sans/pulls
